app:
  name: "go-service-template"
  environment: ${ENVIRONMENT}
server:
  port: 8080
  liveness: "/live"
  readiness: "/ready"
  metrics: "/metrics"
observability:
  enabled: true
  jaeger:
    endpoint: "http://jaeger:14268/api/traces"
postgres:
  host: "postgres"
  port: 5432
  user: "user"
  password: "password"
  name: "database"
  max_connections: 10
  min_connections: 5
  max_idle_time: 10000
  max_conn_lifetime: 10000